name: tus_client_vimeo
description: A tus client for dart allowing resumable uploads using the tus protocol for Vimeo APIs.
version: 1.0.2
homepage: https://github.com/Pinim04/tus_client_vimeo

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.1+4
  http: ^0.13.6
  path: ^1.7.0
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  build_runner: ^2.4.6